version: "3.8"

services:
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - C:/Program Files/PostgreSQL/15/data/:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - netgt
    expose:
      - 5432
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - netgt
    expose:
      - 80
    volumes:
      - C:/convy/env/:/app/
networks:
  netgt:
    driver: bridge
