version: "3.8"
services:
  db:
    image: postgres:15
    ports:
      - "46876:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - netgt
    expose:
      - 5432
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "46877:80"
    depends_on:
      - db
    networks:
      - netgt
    expose:
      - 80
networks:
  netgt:
    driver: bridge
volumes:
  postgres_data:
