version: "3.8"
services:
  db:
    image: postgres:alpine
    ports:
      - "46876:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/convy/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - netgt
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "46877:80"
    depends_on:
      - db
    networks:
      - netgt
networks:
  netgt:
    driver: bridge