name: Deploy

on:
  workflow_dispatch:
jobs:
  prepare-environment:
    runs-on: self-hosted
    steps:
      - name: get source code
        uses: actions/checkout@v3
      - name: Stop and remove containers, networks
        run: docker-compose -f docker-compose.yml down
      - name: Remove unused data
        run: docker system prune -a -f
  deploy:
    runs-on: self-hosted
    needs: prepare-environment
    steps:
      - name: docker-compose
        run: docker-compose --env-file /home/convy/env.properties up -d